//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Espera.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Espera.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artists.
        /// </summary>
        public static string ArtistsViewHeader {
            get {
                return ResourceManager.GetString("ArtistsViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BugReportViewCancel {
            get {
                return ResourceManager.GetString("BugReportViewCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string BugReportViewClose {
            get {
                return ResourceManager.GetString("BugReportViewClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a detailed description of the bug you encountered..
        /// </summary>
        public static string BugReportViewDescriptionWaterMark {
            get {
                return ResourceManager.GetString("BugReportViewDescriptionWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email (optional).
        /// </summary>
        public static string BugReportViewEmail {
            get {
                return ResourceManager.GetString("BugReportViewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        public static string BugReportViewHeader {
            get {
                return ResourceManager.GetString("BugReportViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send a bug report to help improving Espera.
        /// </summary>
        public static string BugReportViewHeader2 {
            get {
                return ResourceManager.GetString("BugReportViewHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string BugReportViewSend {
            get {
                return ResourceManager.GetString("BugReportViewSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending failed.
        /// </summary>
        public static string BugReportViewSendingFailed {
            get {
                return ResourceManager.GetString("BugReportViewSendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending succeeded.
        /// </summary>
        public static string BugReportViewSendingSucceeded {
            get {
                return ResourceManager.GetString("BugReportViewSendingSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug report.
        /// </summary>
        public static string BugReportViewTitle {
            get {
                return ResourceManager.GetString("BugReportViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CrashViewCancel {
            get {
                return ResourceManager.GetString("CrashViewCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CrashViewClose {
            get {
                return ResourceManager.GetString("CrashViewClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string CrashViewDetailExpanderHeader {
            get {
                return ResourceManager.GetString("CrashViewDetailExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Espera has crashed :(.
        /// </summary>
        public static string CrashViewHeader {
            get {
                return ResourceManager.GetString("CrashViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A crash report has been sent!.
        /// </summary>
        public static string CrashViewHeader2AutomaticSent {
            get {
                return ResourceManager.GetString("CrashViewHeader2AutomaticSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send a crash report to help improving Espera.
        /// </summary>
        public static string CrashViewHeader2NotAutomaticSent {
            get {
                return ResourceManager.GetString("CrashViewHeader2NotAutomaticSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string CrashViewSend {
            get {
                return ResourceManager.GetString("CrashViewSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending failed.
        /// </summary>
        public static string CrashViewSendingFailed {
            get {
                return ResourceManager.GetString("CrashViewSendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending succeeded.
        /// </summary>
        public static string CrashViewSendingSucceeded {
            get {
                return ResourceManager.GetString("CrashViewSendingSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espera crashed.
        /// </summary>
        public static string CrashViewTitle {
            get {
                return ResourceManager.GetString("CrashViewTitle", resourceCulture);
            }
        }
    }
}
