//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Espera.View.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Espera.View.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to artists.
        /// </summary>
        public static string ArtistsViewHeader {
            get {
                return ResourceManager.GetString("ArtistsViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BugReportViewCancel {
            get {
                return ResourceManager.GetString("BugReportViewCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string BugReportViewClose {
            get {
                return ResourceManager.GetString("BugReportViewClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a detailed description of the bug you encountered..
        /// </summary>
        public static string BugReportViewDescriptionWaterMark {
            get {
                return ResourceManager.GetString("BugReportViewDescriptionWaterMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email (optional).
        /// </summary>
        public static string BugReportViewEmail {
            get {
                return ResourceManager.GetString("BugReportViewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report a bug.
        /// </summary>
        public static string BugReportViewHeader {
            get {
                return ResourceManager.GetString("BugReportViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send a bug report to help improving Espera.
        /// </summary>
        public static string BugReportViewHeader2 {
            get {
                return ResourceManager.GetString("BugReportViewHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string BugReportViewSend {
            get {
                return ResourceManager.GetString("BugReportViewSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending failed.
        /// </summary>
        public static string BugReportViewSendingFailed {
            get {
                return ResourceManager.GetString("BugReportViewSendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending succeeded.
        /// </summary>
        public static string BugReportViewSendingSucceeded {
            get {
                return ResourceManager.GetString("BugReportViewSendingSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bug report.
        /// </summary>
        public static string BugReportViewTitle {
            get {
                return ResourceManager.GetString("BugReportViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CrashViewCancel {
            get {
                return ResourceManager.GetString("CrashViewCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CrashViewClose {
            get {
                return ResourceManager.GetString("CrashViewClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show details.
        /// </summary>
        public static string CrashViewDetailExpanderHeader {
            get {
                return ResourceManager.GetString("CrashViewDetailExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, Espera has crashed :(.
        /// </summary>
        public static string CrashViewHeader {
            get {
                return ResourceManager.GetString("CrashViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A crash report has been sent!.
        /// </summary>
        public static string CrashViewHeader2AutomaticSent {
            get {
                return ResourceManager.GetString("CrashViewHeader2AutomaticSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can send a crash report to help improving Espera.
        /// </summary>
        public static string CrashViewHeader2NotAutomaticSent {
            get {
                return ResourceManager.GetString("CrashViewHeader2NotAutomaticSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string CrashViewSend {
            get {
                return ResourceManager.GetString("CrashViewSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending failed.
        /// </summary>
        public static string CrashViewSendingFailed {
            get {
                return ResourceManager.GetString("CrashViewSendingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending succeeded.
        /// </summary>
        public static string CrashViewSendingSucceeded {
            get {
                return ResourceManager.GetString("CrashViewSendingSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espera crashed.
        /// </summary>
        public static string CrashViewTitle {
            get {
                return ResourceManager.GetString("CrashViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add songs to the library by going to the Settings (right upper corner, next to the window minimize button) -&amp;gt; Library -&amp;gt; Change Library Path.
        /// </summary>
        public static string LocalViewAddSongHelperMessage {
            get {
                return ResourceManager.GetString("LocalViewAddSongHelperMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to playlist.
        /// </summary>
        public static string LocalViewContextMenuAddToPlaylist {
            get {
                return ResourceManager.GetString("LocalViewContextMenuAddToPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tags.
        /// </summary>
        public static string LocalViewContextMenuEditTags {
            get {
                return ResourceManager.GetString("LocalViewContextMenuEditTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play Now.
        /// </summary>
        public static string LocalViewContextMenuPlayNow {
            get {
                return ResourceManager.GetString("LocalViewContextMenuPlayNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string LocalViewListViewHeaderDuration {
            get {
                return ResourceManager.GetString("LocalViewListViewHeaderDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string LocalViewListViewHeaderGenre {
            get {
                return ResourceManager.GetString("LocalViewListViewHeaderGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string LocalViewListViewHeaderTitle {
            get {
                return ResourceManager.GetString("LocalViewListViewHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accent color.
        /// </summary>
        public static string SettingsViewAccentColorHeader {
            get {
                return ResourceManager.GetString("SettingsViewAccentColorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appearance.
        /// </summary>
        public static string SettingsViewAppearanceHeader {
            get {
                return ResourceManager.GetString("SettingsViewAppearanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my music.
        /// </summary>
        public static string SettingsViewMyMusicHeader {
            get {
                return ResourceManager.GetString("SettingsViewMyMusicHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update library automatically.
        /// </summary>
        public static string SettingsViewMyMusicLibraryUpdateHeader {
            get {
                return ResourceManager.GetString("SettingsViewMyMusicLibraryUpdateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update interval.
        /// </summary>
        public static string SettingsViewMyMusicLibraryUpdateInterval {
            get {
                return ResourceManager.GetString("SettingsViewMyMusicLibraryUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours.
        /// </summary>
        public static string SettingsViewMyMusicLibraryUpdateIntervalHours {
            get {
                return ResourceManager.GetString("SettingsViewMyMusicLibraryUpdateIntervalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default double click action.
        /// </summary>
        public static string SettingsViewMyMusicPlaybackDefaultAction {
            get {
                return ResourceManager.GetString("SettingsViewMyMusicPlaybackDefaultAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playback engine\nChange the playback engine if you experience any sound issues.
        /// </summary>
        public static string SettingsViewMyMusicPlaybackEngine {
            get {
                return ResourceManager.GetString("SettingsViewMyMusicPlaybackEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to playback.
        /// </summary>
        public static string SettingsViewMyMusicPlaybackHeader {
            get {
                return ResourceManager.GetString("SettingsViewMyMusicPlaybackHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change library path.
        /// </summary>
        public static string SettingsViewMyMusicSongSourceChangePath {
            get {
                return ResourceManager.GetString("SettingsViewMyMusicSongSourceChangePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to song source.
        /// </summary>
        public static string SettingsViewMyMusicSongSourceHeader {
            get {
                return ResourceManager.GetString("SettingsViewMyMusicSongSourceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path where Espera searches for songs.
        /// </summary>
        public static string SettingsViewMyMusicSongSourceInfo {
            get {
                return ResourceManager.GetString("SettingsViewMyMusicSongSourceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create administrator.
        /// </summary>
        public static string SettingsViewPartyModeCreateAdministrator {
            get {
                return ResourceManager.GetString("SettingsViewPartyModeCreateAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter party mode.
        /// </summary>
        public static string SettingsViewPartyModeEnterPartyMode {
            get {
                return ResourceManager.GetString("SettingsViewPartyModeEnterPartyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to party mode.
        /// </summary>
        public static string SettingsViewPartyModeHeader {
            get {
                return ResourceManager.GetString("SettingsViewPartyModeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The party mode allows you to lock Espera, so your guests cannot interrupt the playback or change the volume.
        /// </summary>
        public static string SettingsViewPartyModeInfo {
            get {
                return ResourceManager.GetString("SettingsViewPartyModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock playlist.
        /// </summary>
        public static string SettingsViewPartyModeLockPlaylist {
            get {
                return ResourceManager.GetString("SettingsViewPartyModeLockPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock play/pause.
        /// </summary>
        public static string SettingsViewPartyModeLockPlayPause {
            get {
                return ResourceManager.GetString("SettingsViewPartyModeLockPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock time.
        /// </summary>
        public static string SettingsViewPartyModeLockTime {
            get {
                return ResourceManager.GetString("SettingsViewPartyModeLockTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock volume.
        /// </summary>
        public static string SettingsViewPartyModeLockVolume {
            get {
                return ResourceManager.GetString("SettingsViewPartyModeLockVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock window (minimize, maximize, close).
        /// </summary>
        public static string SettingsViewPartyModeLockWindow {
            get {
                return ResourceManager.GetString("SettingsViewPartyModeLockWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make window fullscreen.
        /// </summary>
        public static string SettingsViewPartyModeLockWindowFullscreen {
            get {
                return ResourceManager.GetString("SettingsViewPartyModeLockWindowFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you can enter the party mode,&amp;#10;you have to select a password..
        /// </summary>
        public static string SettingsViewPartyModePasswordInfo {
            get {
                return ResourceManager.GetString("SettingsViewPartyModePasswordInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password.
        /// </summary>
        public static string SettingsViewPartyModePasswordWatermark {
            get {
                return ResourceManager.GetString("SettingsViewPartyModePasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control the playback, volume and playlist with the Android remote control app.\nYou can also let your guests vote on songs and and let them add music from their phones directly to the playlist..
        /// </summary>
        public static string SettingsViewRemoteControlDescription {
            get {
                return ResourceManager.GetString("SettingsViewRemoteControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remote control.
        /// </summary>
        public static string SettingsViewRemoteControlHeader {
            get {
                return ResourceManager.GetString("SettingsViewRemoteControlHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use this option whenever you have Espera displayed on a TV or any other big screen.
        /// </summary>
        public static string SettingsViewScalingDescription {
            get {
                return ResourceManager.GetString("SettingsViewScalingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scaling.
        /// </summary>
        public static string SettingsViewScalingHeader {
            get {
                return ResourceManager.GetString("SettingsViewScalingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to theme.
        /// </summary>
        public static string SettingsViewThemeHeader {
            get {
                return ResourceManager.GetString("SettingsViewThemeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string SettingsViewToggleNo {
            get {
                return ResourceManager.GetString("SettingsViewToggleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string SettingsViewToggleYes {
            get {
                return ResourceManager.GetString("SettingsViewToggleYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change download path.
        /// </summary>
        public static string SettingsViewYoutubeDownloadPathButtonText {
            get {
                return ResourceManager.GetString("SettingsViewYoutubeDownloadPathButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path where Espera downloads the YouTube videos and audio tracks.
        /// </summary>
        public static string SettingsViewYoutubeDownloadPathDescription {
            get {
                return ResourceManager.GetString("SettingsViewYoutubeDownloadPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download path.
        /// </summary>
        public static string SettingsViewYoutubeDownloadPathHeader {
            get {
                return ResourceManager.GetString("SettingsViewYoutubeDownloadPathHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to youtube.
        /// </summary>
        public static string SettingsViewYoutubeHeader {
            get {
                return ResourceManager.GetString("SettingsViewYoutubeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to streaming.
        /// </summary>
        public static string SettingsViewYoutubeStreamingHeader {
            get {
                return ResourceManager.GetString("SettingsViewYoutubeStreamingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always stream highest quality.
        /// </summary>
        public static string SettingsViewYoutubeStreamingHighQualityHeader {
            get {
                return ResourceManager.GetString("SettingsViewYoutubeStreamingHighQualityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming quality.
        /// </summary>
        public static string SettingsViewYoutubeStreamingQuality {
            get {
                return ResourceManager.GetString("SettingsViewYoutubeStreamingQuality", resourceCulture);
            }
        }
    }
}
