﻿using System;
using System.Net.Http;
using System.Collections.Generic;
using System.Linq;
using Refit;

/* ******** Hey You! *********
 *
 * This is a generated file, and gets rewritten every time you build the
 * project. If you want to edit it, you need to edit the mustache template
 * in the Refit package */

namespace RefitInternalGenerated
{
    [AttributeUsage (AttributeTargets.Class | AttributeTargets.Struct | AttributeTargets.Enum | AttributeTargets.Constructor | AttributeTargets.Method | AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Event | AttributeTargets.Interface | AttributeTargets.Delegate)]
    sealed class PreserveAttribute : Attribute
    {
#pragma warning disable 0649
        //
        // Fields
        //
        public bool AllMembers;

        public bool Conditional;
#pragma warning restore 0649
    }
}

namespace Espera.Core
{
    using RefitInternalGenerated;

    [Preserve]
    public partial class AutoGeneratedISoundCloudApi : ISoundCloudApi
    {
        public HttpClient Client { get; protected set; }
        readonly Dictionary<string, Func<HttpClient, object[], object>> methodImpls;

        public AutoGeneratedISoundCloudApi(HttpClient client, IRequestBuilder requestBuilder)
        {
            methodImpls = requestBuilder.InterfaceHttpMethods.ToDictionary(k => k, v => requestBuilder.BuildRestResultFuncForMethod(v));
            Client = client;
        }

        public virtual IObservable<ExploreResponse> GetPopularTracks(int limit)
        {
            var arguments = new object[] { limit };
            return (IObservable<ExploreResponse>) methodImpls["GetPopularTracks"](Client, arguments);
        }

        public virtual IObservable<IReadOnlyList<SoundCloudSong>> Search(string searchTerm,string clientId)
        {
            var arguments = new object[] { searchTerm,clientId };
            return (IObservable<IReadOnlyList<SoundCloudSong>>) methodImpls["Search"](Client, arguments);
        }

    }
}


